### ISSUE TITLE
[Enhancement] Support custom UID:GID

### ISSUE THREAD

**Issue by martadinata666** [nitnelave/lldap#230]
Add support for custom UID/GID.
1. Use gosu
2. Modified entrypoint
3. Will use UID 1000 if not defined by user.

Sample of usage after supported
```
volumes:
  lldap_data:
    driver: local

services:
  lldap:
    image: nitnelave/lldap:stable
    ports:
      # For LDAP
      - "3890:3890"
      # For the web front-end
      - "17170:17170"
    volumes:
      - "lldap_data:/data"
      # Alternatively, you can mount a local folder
      # - "./lldap_data:/data"
    environment:
      - UID=2000 # desired UID
      - GID=3000 # desired GID
      - LLDAP_JWT_SECRET=REPLACE_WITH_RANDOM
      - LLDAP_LDAP_USER_PASS=REPLACE_WITH_PASSWORD
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com
```

Any suggestions?
