### ISSUE TITLE
LLDAP is attempting to chown after updating to 0.4. image.

### ISSUE THREAD

**Issue by grehund** [nitnelave/lldap#237]
It was working fine until the change of image.

> Setup permissions..
chown: changing ownership of '/app': Operation not permitted
chown: changing ownership of '/app/app': Operation not permitted
chown: changing ownership of '/app/app/static': Operation not permitted
chown: changing ownership of '/app/app/static/spinner.gif': Operation not permitted
chown: changing ownership of '/app/app/static/fonts.css': Operation not permitted
chown: changing ownership of '/app/app/static/style.css': Operation not permitted
chown: changing ownership of '/app/app/static/libraries.txt': Operation not permitted
chown: changing ownership of '/app/app/static/fonts': Operation not permitted
chown: changing ownership of '/app/app/static/fonts/fonts.txt': Operation not permitted
chown: changing ownership of '/app/app/pkg': Operation not permitted
chown: changing ownership of '/app/app/pkg/bundle.js': Operation not permitted
chown: changing ownership of '/app/app/pkg/lldap_app_bg.wasm.d.ts': Operation not permitted
chown: changing ownership of '/app/app/pkg/lldap_app_bg.wasm': Operation not permitted
chown: changing ownership of '/app/app/pkg/lldap_app.d.ts': Operation not permitted
chown: changing ownership of '/app/app/pkg/.gitignore': Operation not permitted
chown: changing ownership of '/app/app/pkg/lldap_app.js': Operation not permitted
chown: changing ownership of '/app/app/pkg/package.json': Operation not permitted
chown: changing ownership of '/app/app/index.html': Operation not permitted
chown: changing ownership of '/app/lldap': Operation not permitted
chown: changing ownership of '/app/lldap_config.docker_template.toml': Operation not permitted
chown: changing ownership of '/app/migration-tool': Operation not permitted

**Comment by nitnelave** [comment]
Yes, that was an intentional change to make permission problems less common. What is the issue here? Could you explain why that is a problem and we can find a solution?

**Comment by grehund** [comment]
Have I missed something? I am using the "user:" key to specify a user for the container/service. The user who owns the container has not changed. The file permissions associated with that user within the bind mount haven't changed either. The operation is failing and the container will not start.

**Comment by martadinata666** [comment]
Need update the readme use environment UID and GID

**Comment by nitnelave** [comment]
@grehund Can you try setting the `UID` env variable instead of `user:` ?

**Comment by grehund** [comment]
I tried setting `UID` and `GID` as env vars, it doesn't work on v0.3 or v0.4 that way. I get an error that the volume mount either doesn't exist or can't be written to. 

the `user:` key worked fine and continues to work fine in v0.3.

```
$ ls -ln
total 4
drwxrws---+ 2 1004 1003 4096 Jul 13 12:17 data
```

------------------------------------------
```
version: '3.9'

secrets:
  lldap_jwt_secret:
    external: true
  lldap_user_pass:
    external: true

networks:
  networks_ldap:
    external: true

services:
  lldap:
    image: nitnelave/lldap:v0.4
#    user: "1004:1003"
    secrets:
      - lldap_jwt_secret
      - lldap_user_pass
    networks:
      - networks_ldap
    ports:
      - 3890:3890
      - 17170:17170
    environment:
      - TZ=${TZ}
      - UID=1004
      - GID=1003
      - LLDAP_JWT_SECRET_FILE=/run/secrets/lldap_jwt_secret
      - LLDAP_LDAP_USER_PASS_FILE=/run/secrets/lldap_user_pass
      - LLDAP_LDAP_BASE_DN=dc=local,dc=<REDACTED>,dc=com
    volumes:
      - /<REDACTED>/docker/appdata/lldap/data:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
```
