### ISSUE TITLE
No private keys

### ISSUE THREAD

**Issue by NoverNobida** [nitnelave/lldap#289]
When I enable tls, 
```
[ldaps_options]
enabled=true
port=6360
cert_file="/data/fullchain.pem"
key_file="/data/privkey.pem"
```
```
.
├── data
│   ├── fullchain.pem
│   ├── lldap_config.toml
│   ├── private_key
│   ├── privkey.pem
│   ├── users.db
│   ├── users.db-shm
│   └── users.db-wal
└── docker-compose.yml
```
```
version: '3'

services:
  lldap:
    image: nitnelave/lldap:latest
    container_name: lldap
    ports:
      # For LDAP
      - "3890:3890"
      - "6360:6360"
      # For the web front-end
      - "17170:17170"
    volumes:
      - ./data:/data
    environment:
      - UID=1000
      - GID=1000
      - LLDAP_LDAPS_OPTIONS__PORT=6360
  ```
this error message will appear.
```
[error]: Could not bring up the servers: while binding the LDAP server: while setting up the SSL certificate: No private keys
```
 But I can be sure that my  `CERTIFICATE` and `PRIVATE KEY` is ok because I successfully enable tls for ldaps with these two files in [glauth](https://github.com/glauth/glauth).
