### ISSUE TITLE
Password reset: "Could not send email: Connection error: failed to lookup address information: Name does not resolve"

### ISSUE THREAD

**Issue by Hobbabobba** [nitnelave/lldap#309]
I receive the error message
```
Could not initiate password reset[500 Internal Server Error]: Internal server error: `Could not send email: Connection error: failed to lookup address information: Name does not resolve`
```
when i enter an usename to reset the password.

this is my `docker-compose.yml` file:
```
version: '3'
  lldap:
    image: nitnelave/lldap:latest
    ports:
      # For LDAP
      - "3890:3890"
      # For the web front-end
      - "17170:17170"
    volumes:
      - /home/ubuntu/docker/ldap:/data
    environment:
      - LLDAP_JWT_SECRET=...
      - LLDAP_LDAP_USER_PASS=...
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com
      - LLDAP_HTTP_URL="https://lldap.mydomain.com"
      - LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET=true
      - LLDAP_SMTP_OPTIONS__SERVER="smtp.strato.de"
      - LLDAP_SMTP_OPTIONS__PORT=587
      - LLDAP_SMTP_OPTIONS__TLS_REQUIRED=true
      - LLDAP_SMTP_OPTIONS__USER="myemail@server.com"
      - LLDAP_SMTP_OPTIONS__PASSWORD="password"
```
I double checked and tested the smtp-settings with other applications on the same server and it works.

Any idea what i am missing?
