### ISSUE TITLE
Support read-only `/app` filesystem

### ISSUE THREAD

**Issue by RedlineTriad** [nitnelave/lldap#384]
I am unsure if this is feasible, but it would be nice to support read-only filesystems.
Currently, when starting lldap with a read-only filesystem, it will get to `Setup permissions..` and then print a lot of `chown` errors:
```log
[entrypoint] Copying the default config to /data/lldap_config.toml
[entrypoint] Edit this file to configure LLDAP.
> Setup permissions..
chown: /app: Read-only file system
chown: /app/app: Read-only file system
chown: /app/app/index.html: Read-only file system
...
```

The issue can be reproduced with the following `docker-compose.yml` file:
```yaml
---
version: '3'

services:
  lldap:
    image: nitnelave/lldap:v0.4.1-alpine
    read_only: true
    ports:
      - 17170:17170
    volumes:
      - lldap-data:/data

volumes:
  lldap-data:
```

Read only filesystems are very useful for security, reducing data loss when forgetting to mount data directories, and to reduce disk usage.
It would probably also be nice if it was the default in docker-compose examples.
