### ISSUE TITLE
frontend docker error

### ISSUE THREAD

**Issue by nikhil96widhani** [nitnelave/lldap#41]
Hi thanks for making this. I was looking to something lightweight for my 10 user home-server. Unfortunately i am not able to make it work using docker compose. Here is my compose 

```
services:
  lldap:
    image: nitnelave/lldap
    container_name: lldap
    user: "1000:1000"
    ports:
      # For LDAP
      - 3890:3890
      # For the web front-end
      - 17170:17170
    volumes:
      - /home/test123/volumes/lldap/data:/data
    environment:
      - JWT_SECRET=test123
      - LDAP_USER_PASS=test123
      - LDAP_BASE_DN=dc= test123,dc=com
```

i cannot access web app as i get error: No such file or directory (os error 2)
logs show internal server error
i have also created lldap_config.toml in data dir
