### ISSUE TITLE
Healthcheck?

### ISSUE THREAD

**Issue by JaneJeon** [nitnelave/lldap#451]
Hello, I was wondering what is the best way to go about adding a Docker healthcheck for LLDAP.

Just wget/curl the admin site endpoint? Or is there a /healthz endpoint that I should be hitting instead?

Thank you.

**Comment by nitnelave** [comment]
The CI docker image comes with a health check. Since there are several services to check, and the address depends on the config, it was simpler to implement in the app itself:
```
HEALTHCHECK CMD ["/app/lldap", "run", "--config-file", "/data/lldap_config.toml"]
```

**Comment by JaneJeon** [comment]
Ok, I'll just patiently wait for the next release :)

(I'll leave this open until an official release w/ the healthcheck is released)

**Comment by JaneJeon** [comment]
Wait a minute. Am I reading this correctly?

https://github.com/nitnelave/lldap/blob/main/Dockerfile#L95-L97

It seems to me that you are running the exact same /app/lldap as the entrypoint, with no difference in command (i.e. both are `lldap run --config-file /data/lldap_config.toml`).

So.. is the healthcheck literally just spinning up the app server? Does that not create countless instances of the same app server??

Just trying to understand what is going on here, because from a quick glance, it _seems_ very wrong?

**Comment by JaneJeon** [comment]
And given the existing health endpoint, it seems the correct health cmd should _really_ be:

```
wget --no-verbose --tries=1 --spider http://localhost:17170/health || exit 1
```

I think?

**Comment by martadinata666** [comment]
the latest docker image had `lldap healthcheck` command and return code 200 on success. is it sufficient? or if it work as intended? 🤔 
And taking on compose sample, override the healthcheck parameters.
```
version: "3"

volumes:
  lldap_data:
    driver: local

services:
  lldap:
    image: nitnelave/lldap:stable
    ports:
      # For LDAP
      - "3890:3890"
      # For the web front-end
      - "17170:17170"
    volumes:
      - "lldap_data:/data"
      # Alternatively, you can mount a local folder
      # - "./lldap_data:/data"
    environment:
      - UID=####
      - GID=####
      - TZ=####/####
      - LLDAP_JWT_SECRET=REPLACE_WITH_RANDOM
      - LLDAP_LDAP_USER_PASS=REPLACE_WITH_PASSWORD
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com
    healthcheck:
      test: /app/lldap healthcheck || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
```
