### ISSUE TITLE
When query user `memberof` attribute maybe wrong group dn is returned

### ISSUE THREAD

**Issue by zozzz** [nitnelave/lldap#468]
In this [line](https://github.com/nitnelave/lldap/blob/2593606f1638c2708a9c7db08b0190391ad125c2/server/src/domain/ldap/user.rs#L49) the group common name returned as uid, but the documentation says the group name is `cn=family,ou=groups,dc=example,dc=com`. The memberOf queries is  working like this naming convention.

**Comment by nitnelave** [comment]
Both are valid. Technically, uid is probably more future proof, but it doesn't really matter.

**Comment by zozzz** [comment]
Can you rename it to cn? I want to use with OPNSense, and excepting cn instead of uid. I think this is more standard in group names. Maybe this change breaks other apps.

**Comment by martadinata666** [comment]
you can override `User naming attribute` to `uid`, if that is what you mean of accepting `cn`

**Comment by nitnelave** [comment]
That would more be a request for opnsense, to add support for uid. It's
perfectly standard.

**Comment by zozzz** [comment]
@martadinata666 Not the user name is my problem.

@nitnelave Ok. I just think this is a bug, but just inconsistent _dn_ naming with `(objectClass=groupOfNames)`.

```yaml
# ldapsearch "(objectClass=groupOfNames)"

dn: cn=admin_group,ou=groups,dc=example,dc=com
objectclass: groupOfUniqueNames

dn: cn=lldap_admin,ou=groups,dc=example,dc=com
objectclass: groupOfUniqueNames
```

```yaml
# ldapsearch "(objectClass=person)" memberof

dn: uid=admin,ou=people,dc=example,dc=com
memberof: uid=lldap_admin,ou=groups,dc=example,dc=com

# dn is changed from cn=admin_group,ou=groups,dc=example,dc=com
memberof: uid=admin_group,ou=groups,dc=example,dc=com
```

But, maybe is a good idea to use same _dn_ everywhere.
